version: "3"
services:
  web:
  # replace username/repo:tag with your name and image details
    image: mean-app:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "11055:80"
    networks:
      - webnet
networks:
  webnet:
